---
- name: Установка пакетов
  become: true
  block:
    - name: Обновление списков пакетов
      ansible.builtin.apt:
        update_cache: true

    - name: Установка пакетов на сервера
      ansible.builtin.package:
        name: "{{ item.packages }}"
        state: present
      loop:
        - { group: 'r1_server', packages: "{{ servers.R1.apt_R1 }}" }
        - { group: 'r1_pc', packages: "{{ servers.PC_R1.apt_PC_R1 }}" }
        - { group: 'r0_server', packages: "{{ servers.R0.apt_R0 }}" }
        - { group: 'r0_pc', packages: "{{ servers.PC_R0.apt_PC_R0 }}" }
        - { group: 'r2_server', packages: "{{ servers.R2.apt_R2 }}" }
        - { group: 'r2_pc', packages: "{{ servers.PC_R2.apt_PC_R2 }}" }
      when: inventory_hostname in groups[item.group]
      no_log: true


- name: Изменения сервисов на всех серверах
  become: true
  block:
    - name: Stop firewalld service
      ansible.builtin.service:
        name: firewalld
        state: stopped

    - name: Disable firewalld service
      ansible.builtin.service:
        name: firewalld
        enabled: no
